elt_data_pipeline:
  target: datawarehouse
  outputs:
    datawarehouse:
      type: postgres
      host: datawarehouse
      user: postgres
      password: admin
      port: 5432
      dbname: datawarehouse
      schema: elt_data_pipeline
      threads: 1